BEGIN {
	deep = 0;
}

/^#/ {
	if (deep == 0) {
		print
	}
 
	# notice: the following expressions must occur in the unprocessed stacktraces. the aggregated output is not a good source to find additional regexes (e.g. searching for "libgdal::" doesn't work, since this is generated by pmp)
	if ( \
			(/OGRGeometry::/) || \
			(/OGRLineString::/) || \
			(/OGRPolygon::/) || \
			(/google::sparsetable/) || \
			(/at malloc\.c/) || \
			(/in osmium::io/) || \
			(/in osmium::.*detail/) || \
			(/in std::string/) || \
			(/in std::basic_string/) || \
			(/in std::pair/) || \
			(/in osmium::Timestamp/) || \
			(/in void osmium::detail/) || \
			(/in void osmium::apply/) || \
			(/in \?\?/) || \
			(/libsqlite3\.so\.0/) || \
			(/ from .*libstdc\+\+\.so\.6/) || \
			(/ from \/usr\/lib\/libgdal\.so\.1/) \
	) {
		deep = 1;
	}
}

/^Thread/ {
	print
	deep = 0;
}
